
modLoader="javafml" #mandatory
loaderVersion="[41,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="CC BY-NC-ND 4.0"
[[mods]] #mandatory
modId="projectomnipotence" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Project Omnipotence" #mandatory
authors="ibarnstormer" #optional

# The description text for the mod (multi line!) (#mandatory)
description='''
A mod that allows you to achieve a state of complete harmony with the world around you.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.projectomnipotence]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[41,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.projectomnipotence]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
